#!/bin/python3

# creates template for git-commit

from sys import argv
import subprocess

commit_msg_file = argv[1]

# String → [String]
def run_cmd(cmd):
    return subprocess.run(cmd.split(), stdout=subprocess.PIPE).stdout.decode('utf-8').split('\n')

files_changed = run_cmd("git diff --name-only --cached")

# more fine-grained logic (such as per project, and different conditions) can
# be added
dirs = files_changed[0].split('/')
msg_template = (dirs[len(dirs)-2] if len(dirs) > 1 else "") + ": \n"
with open(commit_msg_file, 'r+') as file:
    old_msg = file.read()
    file.seek(0)
    file.write(msg_template + old_msg)
