vm.swappiness=100
kernel.yama.ptrace_scope = 0
kernel.sysrq=1
kernel.perf_event_paranoid = 1
kernel.dmesg_restrict = 0

# workaround for the annoying mobile operators detecting internet being shared
# from the phone and limiting the traffic
# net.ipv4.ip_default_ttl        = 65
# net.ipv6.conf.enp3s0.hop_limit = 65
# net.ipv6.conf.wlan0.hop_limit  = 65

# Make sure running an app with 80-th port and similar (for devel purposes)
# always works.
net.ipv4.ip_unprivileged_port_start=1

# enable "tcp fast open" for both outgoing and incoming connections
net.ipv4.tcp_fastopen=3

# enable "ecn" for both outgoing and incoming connections
net.ipv4.tcp_ecn=1

# Russia has very poor internet quality, this should somewhat improve it.
# The `fq` is choosen because from various sources it better matches with bbr
# than the default fq_codel
net.ipv4.tcp_congestion_control = bbr
net.core.default_qdisc = fq
